# Generated by Django 2.2.10 on 2020-03-20 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzytkownicy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='zdjecie',
            field=models.ImageField(default='zdjecie.png', upload_to='ustaw_nazwe'),
        ),
    ]
