# Generated by Django 2.2.10 on 2020-03-20 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzytkownicy', '0002_auto_20200320_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='klasa',
            field=models.CharField(choices=[('IA', 'IA'), ('IIA', 'IIA'), ('IIIA', 'IIIA'), ('IB', 'IB'), ('IIB', 'IIB'), ('IIIB', 'IIIB'), ('IC', 'IC'), ('IIC', 'IIC'), ('IIIC', 'IIIC'), ('ID', 'ID'), ('IID', 'IID'), ('IIID', 'IIID'), ('IE', 'IE'), ('IIE', 'IIE'), ('IIIE', 'IIIE'), ('IF', 'IF'), ('IIF', 'IIF'), ('IIIF', 'IIIF')], default='IA', max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profil',
            name='numer_telefonu',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
