# Generated by Django 2.2.10 on 2020-03-20 14:47

from django.db import migrations, models
import uzytkownicy.models


class Migration(migrations.Migration):

    dependencies = [
        ('uzytkownicy', '0003_auto_20200320_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='zdjecie',
            field=models.ImageField(default='zdjecie.png', upload_to=uzytkownicy.models.ustaw_nazwe),
        ),
    ]
