# Generated by Django 2.2.10 on 2020-04-01 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytul', models.CharField(max_length=80)),
                ('tresc', models.TextField()),
                ('przedmiot', models.CharField(choices=[('P', 'Polski'), ('M', 'Matematyka'), ('F', 'Fizyka'), ('I', 'Informatyka'), ('A', 'Angielski')], max_length=1)),
                ('typ_ogloszenia', models.CharField(choices=[('SP', 'Szukam pomocy'), ('OP', 'Oferuję pomoc')], max_length=2)),
                ('typ_pomocy', models.CharField(choices=[('NM', 'Nauka do matury'), ('NS', 'Nauka do sprawdzianu'), ('NL', 'Nauka do lekcji')], max_length=2)),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Oferty',
            },
        ),
        migrations.CreateModel(
            name='Komentarz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tresc', models.TextField()),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('autor', models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('oferta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oferty.Oferta')),
            ],
            options={
                'verbose_name_plural': 'Komentarze',
            },
        ),
    ]
