# Generated by Django 2.2.10 on 2020-03-20 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('oferty', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Komentarz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tresc', models.TextField()),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('autor', models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('oferta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oferty.Oferta')),
            ],
        ),
    ]
