# Generated by Django 2.2.10 on 2020-03-20 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oferty', '0002_komentarz'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='komentarz',
            options={'verbose_name_plural': 'Komentarze'},
        ),
    ]
